default:
  image: openjdk

variables:
  GIT_STRATEGY: clone
  GIT_FETCH_EXTRA_FLAGS: --tags
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - build

build_and_test_job:
  stage: build
  script:
    - ./gradlew assemble
    - ./gradlew test
